name: notifiche_corrispettivi
description: Notifica via mail dei corrispettivi COR10 inviati all'Agenzia delle Entrate dalla cassa dell'area camper.
version: 0.1.0
repository: https://github.com/comune-vermiglio/notifiche-corrispettivi-area-camper
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  xml: ^6.6.0
  http: ^1.5.0
  mailer: ^6.5.0
  equatable: ^2.0.7
  logging: ^1.3.0
  intl: ^0.20.2
  # path: ^1.8.0

dev_dependencies:
  collection: ^1.19.1
  lints: ^5.0.0
  test: ^1.24.0
